baseURL = "https://ootori008.github.io"
languageCode = "ja-jp"
title = "Ootori's Blog"
paginate = 10 # Number of posts per page
theme = "mainroad"

[Author]
  name = "Ootori"
  bio = "とある好奇心旺盛なエンジニア"    
  avatar = "/img/others/avatar.jpg"

[Params]
  subtitle = "Ootoriのブログへようこそ(+_+)"
  description = "Ootori's Personal blog about everything" # Site description. Used in meta description
  copyright = "Ootori" # Footer copyright holder, otherwise will use site title
  toc = true # Enable Table of Contents
  post_navigation = true # Show post navigation at bottom of pages if true
  authorbox = true # Show authorbox at bottom of pages if true
  post_meta = ["date", "categories"]
  hasCJKLanguage = true
  custom_css = ["/css/custom.css"]

  [Params.logo]
    image = "/img/others/avatar.jpg"

  [Params.sidebar]
    home = "right" # Configure layout for home page
    list = "left"  # Configure layout for list pages
    single = false # Configure layout for single pages
    # Enable widgets in given order
    widgets = ["search", "recent", "categories", "taglist", "social"]

  [Params.widgets]
    recent_num = 5 # Set the number of articles in the "Recent articles" widget
    tags_counter = false # Enable counter for each tag in "Tags" widget

  [Params.widgets.social]
    cached = false # activate cache if true
    # Enable parts of social widget
    github = "Ootori008"
    # email = "example@example.com"

  [Params.thumbnail]
    visibility = ["list"] # Control thumbnail visibility